// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repository/banner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/SelferRy/ranking_system/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockBannerRepository is a mock of BannerRepository interface.
type MockBannerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBannerRepositoryMockRecorder
}

// MockBannerRepositoryMockRecorder is the mock recorder for MockBannerRepository.
type MockBannerRepositoryMockRecorder struct {
	mock *MockBannerRepository
}

// NewMockBannerRepository creates a new mock instance.
func NewMockBannerRepository(ctrl *gomock.Controller) *MockBannerRepository {
	mock := &MockBannerRepository{ctrl: ctrl}
	mock.recorder = &MockBannerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBannerRepository) EXPECT() *MockBannerRepositoryMockRecorder {
	return m.recorder
}

// RequestBanner mocks base method.
func (m *MockBannerRepository) RequestBanner(ctx context.Context, slotID entity.SlotID) ([]entity.Banner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestBanner", ctx, slotID)
	ret0, _ := ret[0].([]entity.Banner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestBanner indicates an expected call of RequestBanner.
func (mr *MockBannerRepositoryMockRecorder) RequestBanner(ctx, slotID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestBanner", reflect.TypeOf((*MockBannerRepository)(nil).RequestBanner), ctx, slotID)
}
