logger:
  level: "DEBUG"
  out_paths:
    - "stdout"
  error_output_paths:
    - "stderr"
database:
  type: "sql"
  driver: "postgres"
  host: "localhost"
  port: "5432"
  database: "ranking_system"
  user: "developer"
  password: "devpass"
  ssl: "disable"
  max_conn: 10
  max_idle_conn: 30
  max_lifetime: 1m
server:
  type: "grpc"
  host: "0.0.0.0"
  port: "5080"