logger:
  level: "DEBUG"
  out_paths:
    - "stdout"
#    - "/var/log/ranking_system/app.log"
  error_output_paths:
    - "stderr"
#    - "/var/log/ranking_system/error.log"

database:
  type: "sql"
  driver: "postgres"
  host: "localhost"
  port: "5432"
  database: "ranking_system"
  user: "prod_user"
  password: "prod_password"
  ssl: "disable"
  max_conn: 20
  max_idle_conn: 10
  max_lifetime: 5m

server:
  type: "grpc"
  host: "0.0.0.0"
  port: "5080"

broker:
  brokers:
    - "localhost:9092"
  topic: "ranking_system_topic"